### PR TITLE
#1 #2 recreate spy response to return

### LINKED ISSUE #1: /spy can't respond correctly in some status codes
if API respond 401 status, jsonApiMock can't handle it.

``` java
java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1636) ~[na:1.8.0_25]
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439) ~[na:1.8.0_25]
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_25]
    at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:48) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at itaka.api.mock.logic.SpyRestTemplateErrorHandler.hasError(SpyRestTemplateErrorHandler.java:18) ~[classes/:na]
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:629) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.7.RELEASE.jar:4.2.7.RELEASE]
    at itaka.api.mock.logic.ApiSpy.callAPI(ApiSpy.java:96) ~[classes/:na]
```

### PR DESCRIPTION
**Pull request by IsaoTakahashi**
resolve #1 and #2 .

### CODE REVIEW

File: src/main/java/itaka/api/mock/controller/SupportController.java [hunk 1]
```diff
@@ -15,22 +15,22 @@
 @Slf4j
 public class SupportController {
 
-    @RequestMapping(value = "/data", method = RequestMethod.GET)
```
Comment (IsaoTakahashi) [inline src/main/java/itaka/api/mock/controller/SupportController.java:18]: remove unnecessary "/"

File: src/main/java/itaka/api/mock/logic/ApiSpy.java [hunk 2]
```diff
@@ -35,9 +34,10 @@
 
     private RestTemplate restTemplate;
 
-    public ApiSpy(){
+    public ApiSpy() {
         restTemplate = new RestTemplate();
         restTemplate.setErrorHandler(new SpyRestTemplateErrorHandler());
+        restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory());
```
Comment (IsaoTakahashi) [inline src/main/java/itaka/api/mock/logic/ApiSpy.java:40]: add RequestFactory to handle some 401 response.

File: src/main/java/itaka/api/mock/logic/ApiSpy.java [hunk 3]
```diff
@@ -90,4 +88,11 @@ public ApiSpy(){
                 entity,
                 String.class);
     }
+
+    private ResponseEntity<String> createResponse(ResponseEntity<String> apiEntity) {
```
Comment (IsaoTakahashi) [inline src/main/java/itaka/api/mock/logic/ApiSpy.java:92]: recreate ResponseEntity to cut some Response Headers.
